name: Build and Publish (dev builds)

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths-ignore:
      - "docs/**"

jobs:
  build:

    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: fwilhe2/setup-kotlin@main

      - name: Make gradlewexecutable
        run: chmod +x ./gradlew

      - name: Make deploy script executable0
        run: chmod +x ./deploy.kts

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Kotlin deploy script
        run: kotlin ./deploy.kts
        env:
          build_number: ${{ github.run_number }}
          build_vcs_number: ${{ github.sha }}
          branch: ${{ github.ref }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test 

      - name: Copy files
        run: |
          mkdir export/
          mkdir export/connectors/
          mkdir export/modules/
          cp -r api-files/ export/
          cp connectors/*-connector/build/libs/*.jar export/connectors/
          cp services/node-service/build/libs/redicloud-node-service-*.jar export/
          cp -r start-scripts/ export/
          cp modules/*/build/libs/*.jar export/modules/
          rm export/modules/*module-handler*.jar
      - name: Publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
        env:
          token: ${{ github.token }}
          username: Suqatri
          repository: ${{ github.repository }}

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: redicloud
          path: export/
